// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/v1/calculator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CalculationRequest contains the two numbers to be calculated.
type CalculationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number1       float64                `protobuf:"fixed64,1,opt,name=number1,proto3" json:"number1,omitempty"`
	Number2       float64                `protobuf:"fixed64,2,opt,name=number2,proto3" json:"number2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculationRequest) Reset() {
	*x = CalculationRequest{}
	mi := &file_api_proto_v1_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculationRequest) ProtoMessage() {}

func (x *CalculationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculationRequest.ProtoReflect.Descriptor instead.
func (*CalculationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *CalculationRequest) GetNumber1() float64 {
	if x != nil {
		return x.Number1
	}
	return 0
}

func (x *CalculationRequest) GetNumber2() float64 {
	if x != nil {
		return x.Number2
	}
	return 0
}

// CalculationResponse contains the result of the calculation.
type CalculationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        float64                `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculationResponse) Reset() {
	*x = CalculationResponse{}
	mi := &file_api_proto_v1_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculationResponse) ProtoMessage() {}

func (x *CalculationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculationResponse.ProtoReflect.Descriptor instead.
func (*CalculationResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *CalculationResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_api_proto_v1_calculator_proto protoreflect.FileDescriptor

const file_api_proto_v1_calculator_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/v1/calculator.proto\x12\rcalculator.v1\"H\n" +
	"\x12CalculationRequest\x12\x18\n" +
	"\anumber1\x18\x01 \x01(\x01R\anumber1\x12\x18\n" +
	"\anumber2\x18\x02 \x01(\x01R\anumber2\"-\n" +
	"\x13CalculationResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x01R\x06result2\xd8\x02\n" +
	"\x11CalculatorService\x12L\n" +
	"\x03Add\x12!.calculator.v1.CalculationRequest\x1a\".calculator.v1.CalculationResponse\x12Q\n" +
	"\bSubtract\x12!.calculator.v1.CalculationRequest\x1a\".calculator.v1.CalculationResponse\x12Q\n" +
	"\bMultiply\x12!.calculator.v1.CalculationRequest\x1a\".calculator.v1.CalculationResponse\x12O\n" +
	"\x06Divide\x12!.calculator.v1.CalculationRequest\x1a\".calculator.v1.CalculationResponseB\x10Z\x0e./internal/pb/b\x06proto3"

var (
	file_api_proto_v1_calculator_proto_rawDescOnce sync.Once
	file_api_proto_v1_calculator_proto_rawDescData []byte
)

func file_api_proto_v1_calculator_proto_rawDescGZIP() []byte {
	file_api_proto_v1_calculator_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_calculator_proto_rawDesc), len(file_api_proto_v1_calculator_proto_rawDesc)))
	})
	return file_api_proto_v1_calculator_proto_rawDescData
}

var file_api_proto_v1_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_v1_calculator_proto_goTypes = []any{
	(*CalculationRequest)(nil),  // 0: calculator.v1.CalculationRequest
	(*CalculationResponse)(nil), // 1: calculator.v1.CalculationResponse
}
var file_api_proto_v1_calculator_proto_depIdxs = []int32{
	0, // 0: calculator.v1.CalculatorService.Add:input_type -> calculator.v1.CalculationRequest
	0, // 1: calculator.v1.CalculatorService.Subtract:input_type -> calculator.v1.CalculationRequest
	0, // 2: calculator.v1.CalculatorService.Multiply:input_type -> calculator.v1.CalculationRequest
	0, // 3: calculator.v1.CalculatorService.Divide:input_type -> calculator.v1.CalculationRequest
	1, // 4: calculator.v1.CalculatorService.Add:output_type -> calculator.v1.CalculationResponse
	1, // 5: calculator.v1.CalculatorService.Subtract:output_type -> calculator.v1.CalculationResponse
	1, // 6: calculator.v1.CalculatorService.Multiply:output_type -> calculator.v1.CalculationResponse
	1, // 7: calculator.v1.CalculatorService.Divide:output_type -> calculator.v1.CalculationResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_calculator_proto_init() }
func file_api_proto_v1_calculator_proto_init() {
	if File_api_proto_v1_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_calculator_proto_rawDesc), len(file_api_proto_v1_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_calculator_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_calculator_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_calculator_proto_msgTypes,
	}.Build()
	File_api_proto_v1_calculator_proto = out.File
	file_api_proto_v1_calculator_proto_goTypes = nil
	file_api_proto_v1_calculator_proto_depIdxs = nil
}
